### PR TITLE
Update locality and neighbourhood records in PK

### PR DESCRIPTION
**Pull request by stepps00**
Will fix https://github.com/whosonfirst-data/whosonfirst-data/issues/1735.

This PR will:

- [x] Add polygons to 430+  populous localities in Pakistan
- [x] Add 1100+ neighbourhood records to some major cities in Pakistan
- [x] Update a handful of bunk locality/neighbourhood records in WOF
- [x] Add localizations to updated features
- [x] PIP records to update hierarchies
- [x] Validate records

### CODE REVIEW

**Comment by stepps00** [comment]
New neighbourhoods in Islamabad and surrounding area
Screen Shot 2022-08-01 at 5 18 33 PM

New neighbourhoods in Pashawar
Screen Shot 2022-08-01 at 5 18 42 PM

New neighbourhoods in Lahore
Screen Shot 2022-08-01 at 5 18 13 PM

New neighbourhoods in Karachi
Screen Shot 2022-08-01 at 5 18 00 PM

Locality coverage
Screen Shot 2022-08-01 at 5 17 35 PM

**Comment by stepps00** [comment]
Aside from PIP work and localized name additions I'd like to add, this PR is ready for review.

**Review by nvkelso — APPROVED** [review]
LGTM, headed in right direction and great to see all the new neighbourhoods :)

**Comment by stepps00** [comment]
The most recent commit includes name translations in Urdu, and backfills some English name properties.
I'll PIP and validate this PR, and merge once that work is complete.

**Comment by stepps00** [comment]
The most recent commit includes all the PIP work / hierarchy updates needed for this branch. I've also validated all the changes in this PR.

Will review the changes again, then merge.

**Pull request merged**
